<a href="https://colab.research.google.com/github/hyunicecream/ML-DL/blob/main/Bagging(iris_Data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import classification_report
import numpy as np

In [ ]:
# 데이터 로드
iris = load_iris()

In [ ]:
# train, tst 데이터 세트를 구성한다.
trainX, testX, trainY, testY = train_test_split(iris['data'], iris['target'], test_size=0.2)

In [ ]:
# 4가지의 모델을 생성한다. KNN, Decision tree, SVM, Logistic Regression
knn = KNeighborsClassifier(n_neighbors=5, p =2, metric='minkowski')
dtree = DecisionTreeClassifier(criterion='gini', max_depth=8)
svm = SVC(kernel='rbf', gamma=0.1, C=1.0, probability=True)
lreg = LogisticRegression(max_iter=500)

In [ ]:
# 4가지 모델로 Bagging을 구성하고, 각 모델의 추정 확률을 누적한다.
prob = np.zeros((testY.shape[0], iris.target_names.shape[0]))
base_model = [knn, dtree, svm, lreg]
for i in base_model:
  bag = BaggingClassifier(base_estimator=i, n_estimators=100, bootstrap=True)
  bag.fit(trainX, trainY)

  prob += bag.predict_proba(testX)

In [ ]:
# 확률의 누적합이 가장 큰 class를 찾고, 정확도를 측정한다.
predY = np.argmax(prob, axis=1)
predY

array([1, 1, 0, 0, 1, 2, 1, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 1, 0, 1, 1,
       2, 0, 0, 2, 2, 0, 0, 0])

In [ ]:
# 시험데이터의 Confusion matrix를 작성한다.(row : actual, col : predict)
print('\nConfusion matrix :')
print(confusion_matrix(testY, predY))
print()
print(classification_report(testY, predY, target_names=iris.target_names))


Confusion matrix :
[[10  0  0]
 [ 0  7  0]
 [ 0  1 12]]

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.88      1.00      0.93         7
   virginica       1.00      0.92      0.96        13

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
from sklearn.metrics import accuracy_score

print(' Accuracy = %.2f' % accuracy_score(testY, predY))

 Accuracy = 0.97
