<a href="https://colab.research.google.com/github/hyunicecream/ML-DL/blob/main/Majority%20Voting(iris_Data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import  classification_report
from sklearn.linear_model import LogisticRegression
import numpy as np

In [ ]:
# iris데이터 불러오기
iris = load_iris()

In [ ]:
# train, test셋을 구성한다.
trainX, testX, trainY, testY = train_test_split(iris['data'], iris['target'], test_size = 0.2)

In [ ]:
# 4가지 모델로 구성
knn = KNeighborsClassifier(n_neighbors = 5, p = 2, metric='minkowski')
dtree = DecisionTreeClassifier(criterion= 'gini', max_depth=8)
svm = SVC(kernel='rbf', gamma=0.1, C=1.0, probability=True)
lreg = LogisticRegression(max_iter=500)

base_model = [('knn', knn), ('dtree', dtree), ('svm', svm), ('lreg', lreg)]
ensemble = VotingClassifier(estimators=base_model, voting='soft')
ensemble.fit(trainX, trainY)

VotingClassifier(estimators=[('knn', KNeighborsClassifier()),
                             ('dtree', DecisionTreeClassifier(max_depth=8)),
                             ('svm', SVC(gamma=0.1, probability=True)),
                             ('lreg', LogisticRegression(max_iter=500))],
                 voting='soft')

In [ ]:
print('학습 데이터의 정확도 = %.2f' % ensemble.score(trainX, trainY))
print('시험 데이터의 정확도 = %.2f' % ensemble.score(testX, testY))

학습 데이터의 정확도 = 0.99
시험 데이터의 정확도 = 0.93


In [ ]:
# 시험데이터의 Confusion matrix를 작성한다.
predY = ensemble.predict(testX)
print('\n')
print('Confusion matrix :')
print(confusion_matrix(testY, predY))
print()
print(classification_report(testY, predY, target_names=iris.target_names))



Confusion matrix :
[[10  0  0]
 [ 0 11  0]
 [ 0  2  7]]

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.85      1.00      0.92        11
   virginica       1.00      0.78      0.88         9

    accuracy                           0.93        30
   macro avg       0.95      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

